<?php

namespace AppBundle\Repository;

use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

/**
 * RuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RuleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllRulesBySymbol()
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT r.symbol FROM AppBundle:Rule r
                WHERE r.isDone = :isDone
                ORDER BY r.symbol  ASC GROUP BY r.symbol'
            )->setParameter('isDone', 0);
        return $query->getResult();

    }

    public function countUserRulesBySymbol($where = array())
    {
        try {
            return $this->createQueryBuilder('r')
                ->andWhere('r.isDone = :isDone')
                ->andWhere('r.user = :user')
                ->andWhere('r.symbol = :symbol')
                ->setParameter('isDone', $where['isDone'])
                ->setParameter('user', $where['user'])
                ->setParameter('symbol', $where['symbol'])
                ->select('COUNT(r.id) as ruleId')
                ->getQuery()
                ->getSingleScalarResult();
        } catch (NoResultException $e) {
        } catch (NonUniqueResultException $e) {
        }

    }
}
