<?php

namespace AppBundle\Repository;

/**
 * RuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RuleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllRulesBySymbol()
    {
        $query = $this->getEntityManager()
            ->createQuery(
                'SELECT r.symbol FROM AppBundle:Rule r
                WHERE r.isDone = :isDone
                ORDER BY r.symbol  ASC GROUP BY r.symbol'
            )->setParameter('isDone', 0);
        return $query->getResult();

    }
}
